---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- directory: !format "Applications/QSVC/%SERVICE%"
  children:
  - name: !format "qsvc-%service%-war"
    type: udm.Application
    children:
    - name: !value appversion
      type: udm.DeploymentPackage
      children:
      - name: !format "%service%"
        type: jee.War
        scanPlaceholders: true
        file: !file "./war/customer-agreement-3.1.3.war"
        tags: 
        - !format "%profile%"
      - name: !format "%service%.properties"
        type: tomcat.ConfigurationFile
        fileEncodings:
          ".+\\.properties": ISO-8859-1
        targetDirectory: !format "/Users/elmos/work/softs/%profile%/parm"
        file: !file "./parm/config.properties"
        tags: 
        - !format "%profile%"
      - name: !format "%profile%.reload.orderpassing"
        type: advcmd.Command
        command: echo "reload orderpassing"
        createOrder: "100"
        destroyOrder: "40"
        alwaysRun: "true"
        noopOrder: "100"
        tags: 
        - !format "%profile%"