apiVersion: xl-deploy/v1
kind: Environments
spec:
- directory: !format "Environments/OPTIMA/QSVC/DEV/%PROFILE%"
  children:
    - name: !format "OPTIMA_QSVC_DEV_%PROFILE%_DICT"
      type: udm.Dictionary
      entries:
        qsvc.home: !value home
        qsvc.profile.name: !value profile
        qsvc.profile.home: !format "%home%/%profile%"
        qsvc.profile.start: !format "%home%/scripts/start.sh"
        qsvc.profile.stop: !format "%home%/scripts/stop.sh"
        qsvc.profile.adminapp.reload: !format "%home%/scripts/adminapp.sh reload "
        qsvc.profile.adminapp.check: !format "%home%/scripts/adminapp.sh check "
        qsvc.profile.tomcat.name: !value tomcatnode
        qsvc.profile.tomcat.port.http: !value porthttp
        qsvc.profile.tomcat.port.https: !value porthttps
    - name: !format "OPTIMA_QSVC_DEV_%PROFILE%_ENV"
      type: udm.Environment
      members:
      - !format "~Infrastructure/OPTIMA/QSVC/DEV/%PROFILE%/host-vm/%profile%.tomcat/%profile%.tomcat.vh"
      - !format "~Infrastructure/OPTIMA/QSVC/DEV/%PROFILE%/host-vm/%profile%.tomcat"
      - !format "~Infrastructure/OPTIMA/QSVC/DEV/%PROFILE%/host-vm"
      dictionaries:
      - !format "~Environments/OPTIMA/QSVC/DEV/%PROFILE%/OPTIMA_QSVC_DEV_%PROFILE%_DICT"
