---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- directory: !format "Applications/%QSVC%/%PROFILE%"
  children:
  - name: !format "qsvc-%profile%-scripts"
    type: udm.Application
    children:
    - name: !value appversion
      type: udm.DeploymentPackage
      children:
      - name: !format "%profile%.scripts"
        type: file.Folder
        fileEncodings:
          ".+\\.properties": ISO-8859-1
        targetPath: !format "{{qsvc.profile.home}}/scripts"
        file: !file "./profile-scripts"
        tags: 
        - qsvc.cmd