---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- directory: !format "Applications/%QSVC%/%PROFILE%/%SERVICE%"
  children:
  - name: !format "qsvc-%service%-war"
    type: udm.Application
    children:
    - name: !value appversion
      type: udm.DeploymentPackage
      children:
      - name: !format "%service%"
        type: jee.War
        scanPlaceholders: true
        file: !file "./war/customer-agreement-3.1.3.war"
        tags: 
        - !format "%profile%"
      - name: !format "%service%.parm"
        type: file.Folder
        fileEncodings:
          ".+\\.properties": ISO-8859-1
        targetPath: !format "{{qsvc.profile.home}}/parm"
        file: !file "./parm"
        tags: 
        - !format "%profile%"
      - name: !format "%profile%.reload.%service%"
        type: advcmd.Command
        command: echo "{{qsvc.profile.adminapp.reload}}"
        createOrder: "100"
        destroyOrder: "40"
        alwaysRun: "true"
        noopOrder: "100"
        tags: 
        - !format "%profile%"