---
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- directory: !format "Infrastructure/OPTIMA/QSVC/DEV/%PROFILE%"
  children:
  - name: host-vm
    type: overthere.SshHost
    os: UNIX
    address: deployit.vm
    username: elmos
    password: pass2000+!
    tags: 
    - !format "%profile%"
    children:
    - name: !format "%profile%.tomcat"
      type: tomcat.Server
      home: !format "/Users/elmos/work/softs/%profile%/tdcom%profile%"
      startCommand: echo " not used, reload used instead"
      stopCommand: echo " not used, reload used instead"
      tags: 
      - !format "%profile%"
      children:
        - name: !format "%profile%.tomcat.vh"
          type: tomcat.VirtualHost
          tags: 
          - !format "%profile%"
