---
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- directory: !format "Infrastructure/%POOL%/%QSVC%/%ENV%"
  children:
  - name: !format "host-vm-%PROFILE%-%server%"
    type: overthere.SshHost
    os: UNIX
    address: deployit.vm
    username: elmos
    password: pass2000+!
    tags: 
    - !format "%profile%"
    children:
    - name: !format "%profile%.tomcat" 
      type: tomcat.Server
      tags:
      - !format "%profile%"
      home: !format "%home%/%profile%/%tomcatnode%"
      startCommand: "echo \" not used, reload used instead\""
      stopCommand: "echo \" not used, reload used instead\""
      children:
      - name: !format "%profile%.tomcat.vh"
        type: tomcat.VirtualHost
        tags:
        - !format "%profile%"