---
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- directory: !format "Infrastructure/%POOL%/%QSVC%/%ENV%"
  children:
  - name: !format "host-vm-%server%"
    type: overthere.SshHost
    os: UNIX
    address: deployit.vm
    username: elmos
    password: pass2000+!
    tags: 
    - qsvc.cmd
